version: '2'
services:
    gost-db:
        image: geodan/gost-db
        volumes:
            - postgis:/var/lib/pgsql/9.5/data
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    gost:
        image: geodan/gost
    dashboard:
        image: geodan/gost-dashboard
        ports:
          - "8080:8080"
volumes:
    postgis: {}
